### ISSUE TITLE
请教一些文章相关的问题

### ISSUE THREAD

**Issue by ithok** [cmaxhao/DCF#1]
作者您好，感谢您的工作，关于分歧正则化的显式定义对我很有启发。
以及，想向您请教一下我在看这篇文章遇到的一些问题。
1.本文是否还属于狭义上的协同过滤？因为据我所知CF一般是只从交互数据出发并不引入额外属性，比如KGAT、KGCN都并不claim自己是协同过滤，只是引入知识图作为手段来改进推荐，但是本文中给我的感觉可能定义有点模糊。
2.关于4.2节内容中的头部实体v，Π(u,r,t）这个注意力系数是怎么计算的，即如何将用户引入作为上下文。r，t来自KG图部分，u是交互部分，这两者怎么联系在一起，因为我暂时还没有看代码，所以不是很能理解。
望您不吝赐教

**Comment by cmaxhao** [comment]
同学您好，首先感谢您对我们工作的关注和支持，下面解答下您的疑惑。 
1、DCF的出发点是将用户和物品的表达分为显式和隐式两种，然后通过KG和GCN来建模得到更优的用户和物品表达， KGAT、KGCN不觉得自己是协同过滤是因为侧重点在GCN处，通过GCN挖掘beyond 简单的用户-物品交互获得更深层次的用户-物品关系。 
2、让用户当上下文是为了让用户的表达来决定每一个实体-关系对的重要性（通过内积或者预先相似度体现），其实此处可以做的更丰富、更充分，使用分层注意力，不过就更复杂了。 
祝好！ 

发件人: "kela" ***@***.***> 
收件人: "cmaxhao/DCF" ***@***.***> 
抄送: "Subscribed" ***@***.***> 
发送时间: 星期三, 2022年 6 月 08日 下午 4:07:37 
主题: [cmaxhao/DCF] 请教一些文章相关的问题 (Issue #1) 





作者您好，感谢您的工作，关于分歧正则化的显式定义对我很有启发。 
以及，想向您请教一下我在看这篇文章遇到的一些问题。 
1.本文是否还属于狭义上的协同过滤？因为据我所知CF一般是只从交互数据出发并不引入额外属性，比如KGAT、KGCN都并不claim自己是协同过滤，只是引入知识图作为手段来改进推荐，但是本文中给我的感觉可能定义有点模糊。 
2.关于4.2节内容中的头部实体v，Π(u,r,t）这个注意力系数是怎么计算的，即如何将用户引入作为上下文。r，t来自KG图部分，u是交互部分，这两者怎么联系在一起，因为我暂时还没有看代码，所以不是很能理解。 
望您不吝赐教

**Comment by ithok** [comment]
好的，感谢您的回复！
